//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PipeExplorer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PipeExplorer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to before {0}.
        /// </summary>
        public static string DateCreatedUpToFormatted {
            get {
                return ResourceManager.GetString("DateCreatedUpToFormatted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to access Windows Registry.
        /// </summary>
        public static string ErrorAccessingRegistry {
            get {
                return ResourceManager.GetString("ErrorAccessingRegistry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not save settings..
        /// </summary>
        public static string ErrorCouldNotSaveSettings {
            get {
                return ResourceManager.GetString("ErrorCouldNotSaveSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not save settings: {0}.
        /// </summary>
        public static string ErrorCouldNotSaveSettingsFormatted {
            get {
                return ResourceManager.GetString("ErrorCouldNotSaveSettingsFormatted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be larger than or equal to zero.
        /// </summary>
        public static string ErrorMustBeNonNegative {
            get {
                return ResourceManager.GetString("ErrorMustBeNonNegative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be larger than zero фыфы.
        /// </summary>
        public static string ErrorMustBePositive {
            get {
                return ResourceManager.GetString("ErrorMustBePositive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        public static string PipeListHeaderComment {
            get {
                return ResourceManager.GetString("PipeListHeaderComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connections.
        /// </summary>
        public static string PipeListHeaderConnections {
            get {
                return ResourceManager.GetString("PipeListHeaderConnections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created.
        /// </summary>
        public static string PipeListHeaderCreated {
            get {
                return ResourceManager.GetString("PipeListHeaderCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string PipeListHeaderName {
            get {
                return ResourceManager.GetString("PipeListHeaderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter by name.
        /// </summary>
        public static string QuickFilter {
            get {
                return ResourceManager.GetString("QuickFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Highlight duration.
        /// </summary>
        public static string SettingsHighlightDuration {
            get {
                return ResourceManager.GetString("SettingsHighlightDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh interval.
        /// </summary>
        public static string SettingsRefreshInterval {
            get {
                return ResourceManager.GetString("SettingsRefreshInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} sec..
        /// </summary>
        public static string SettingsRefreshIntervalStringFormat {
            get {
                return ResourceManager.GetString("SettingsRefreshIntervalStringFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At startup.
        /// </summary>
        public static string SettingsStartImmediatelyHeader {
            get {
                return ResourceManager.GetString("SettingsStartImmediatelyHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not start scanning immediately.
        /// </summary>
        public static string SettingsStartImmediatelyOff {
            get {
                return ResourceManager.GetString("SettingsStartImmediatelyOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start scanning immediately.
        /// </summary>
        public static string SettingsStartImmediatelyOn {
            get {
                return ResourceManager.GetString("SettingsStartImmediatelyOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string StartButtonText {
            get {
                return ResourceManager.GetString("StartButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        public static string StopButtonText {
            get {
                return ResourceManager.GetString("StopButtonText", resourceCulture);
            }
        }
    }
}
